document.write('<!-- BEGIN Site Header -->\n');
document.write('        <div class=\"site-header fixed-top\">\n');
document.write('            <div class=\"container-fluid\">\n');
document.write('                <div class=\"header-inner d-flex justify-content-between align-items-center px-2\">\n');
document.write('                    <!-- BEGIN Header Nav Start -->\n');
document.write('                    <ul class=\"nav header-nav-main align-items-center header-nav-start\">\n');
document.write('                        <li class=\"nav-item item-sidebar-toggle me-3\">\n');
document.write('                            <a href=\"#\" class=\"nav-link px-1\"><i class=\"fa-solid fa-bars\"></i></a>\n');
document.write('                        </li>\n');
document.write('                        <li class=\"nav-item item-search d-none d-lg-inline-flex\">\n');
document.write('                            <div class=\"input-group input-group-fake-input input-group-search rounded-circle\">\n');
document.write('                                <span class=\"input-group-text border-end-0 pe-0 ps-3\"><i class=\"fa-solid fa-search opacity-50\"></i></span>\n');
document.write('                                <input type=\"text\" class=\"form-control border-start-0\" value=\"\" placeholder=\"Tìm kiếm\">\n');
document.write('                            </div>\n');
document.write('                        </li>\n');
document.write('                    </ul>\n');
document.write('                    <!-- END Header Nav Start -->\n');
document.write('                    <!-- BEGIN Header Nav End -->\n');
document.write('                    <ul class=\"nav header-nav-main align-items-center header-nav-end\">\n');
document.write('                        <li class=\"nav-item item-notification dropdown no-arrow has-new-notication\">\n');
document.write('                            <a href=\"#\" class=\"nav-link dropdown-toggle\" data-bs-toggle=\"dropdown\" data-bs-auto-close=\"outside\" aria-expanded=\"false\"><span class=\"icon text-secondary\"><i class=\"fa-solid fa-bell\"></i></span></a>\n');
document.write('                            <div class=\"dropdown-menu pt-0\">\n');
document.write('                                <!-- BEGIN Notifiation Header -->\n');
document.write('                                <div class=\"py-2 px-3 border-bottom d-flex justify-content-between align-items-center border-radius-top bg-light\">\n');
document.write('                                    <h6 class=\"text-primary text-uppercase mb-0\"><strong>Thông báo</strong></h6>\n');
document.write('                                    <a href=\"#\" class=\"small\">Đánh dấu đã đọc</a>\n');
document.write('                                </div>\n');
document.write('                                <!-- END Notifiation Header -->\n');
document.write('                                <div class=\"py-1 px-3 border-bottom\"><span class=\"opacity-50\">Hôm nay</span></div>\n');
document.write('                                <!-- BEGIN List Notifiation -->\n');
document.write('                                <div class=\"list-notificaitons list-group list-group-flush\">\n');
document.write('                                    <!-- BEGIN Item -->\n');
document.write('                                    <a href=\"#\" class=\"list-group-item list-group-item-action unread\">\n');
document.write('                                        <div class=\"d-flex\">\n');
document.write('                                            <div class=\"flex-shrink-1 me-3\">\n');
document.write('                                                <img src=\"img/temp/40x40.jpg\" class=\"mt-1\" alt=\"\">\n');
document.write('                                            </div>\n');
document.write('                                            <div class=\"flex-grow-1\">\n');
document.write('                                                <p class=\"mb-1\">Ut vel nibh sit amet dolor hendrerit vestibulum.</p>\n');
document.write('                                                <span class=\"small opacity-50\">1 giớ trước</span>\n');
document.write('                                            </div>\n');
document.write('                                        </div>\n');
document.write('                                    </a>\n');
document.write('                                    <!-- END Item -->\n');
document.write('                                    <!-- BEGIN Item -->\n');
document.write('                                    <a href=\"#\" class=\"list-group-item list-group-item-action unread\">\n');
document.write('                                        <div class=\"d-flex\">\n');
document.write('                                            <div class=\"flex-shrink-1 me-3\">\n');
document.write('                                                <img src=\"img/temp/40x40.jpg\" class=\"mt-1\" alt=\"\">\n');
document.write('                                            </div>\n');
document.write('                                            <div class=\"flex-grow-1\">\n');
document.write('                                                <p class=\"mb-1\">Ut vel nibh sit amet dolor hendrerit vestibulum.</p>\n');
document.write('                                                <span class=\"small opacity-50\">1 giớ trước</span>\n');
document.write('                                            </div>\n');
document.write('                                        </div>\n');
document.write('                                    </a>\n');
document.write('                                    <!-- END Item -->\n');
document.write('                                    <!-- BEGIN Item -->\n');
document.write('                                    <a href=\"#\" class=\"list-group-item list-group-item-action\">\n');
document.write('                                        <div class=\"d-flex\">\n');
document.write('                                            <div class=\"flex-shrink-1 me-3\">\n');
document.write('                                                <img src=\"temp/40x40.jpg\" class=\"mt-1\" alt=\"\">\n');
document.write('                                            </div>\n');
document.write('                                            <div class=\"flex-grow-1\">\n');
document.write('                                                <p class=\"mb-1\">Ut vel nibh sit amet dolor hendrerit vestibulum.</p>\n');
document.write('                                                <span class=\"small opacity-50\">1 giớ trước</span>\n');
document.write('                                            </div>\n');
document.write('                                        </div>\n');
document.write('                                    </a>\n');
document.write('                                    <!-- END Item -->\n');
document.write('                                </div>\n');
document.write('                                <!-- END List Notifiation -->\n');
document.write('                                <div class=\"pt-1 px-3 text-center border-top\">\n');
document.write('                                    <a href=\"#\" class=\"small\">Xem tất cả</a>\n');
document.write('                                </div>\n');
document.write('                            </div>\n');
document.write('                        </li>\n');
document.write('                        <li class=\"nav-item item-user dropdown no-arrow ms-2\">\n');
document.write('                            <a href=\"#\" class=\"nav-link dropdown-toggle px-0\" data-bs-toggle=\"dropdown\" data-bs-auto-close=\"outside\" aria-expanded=\"false\"><img src=\"img/temp/32x32.jpg\" class=\"rounded-circle\" alt=\"\"></a>\n');
document.write('                            <ul class=\"dropdown-menu dropdown-menu-end\">\n');
document.write('                                <li class=\"py-2 px-3\">\n');
document.write('                                    <p class=\"text-center mb-1\">\n');
document.write('                                        <a href=\"#\"><img src=\"img/temp/64x64.jpg\" class=\"rounded-circle\" alt=\"\"></a>\n');
document.write('                                    </p>\n');
document.write('                                    <p class=\"text-center mb-1\"><strong>Mercedes Gilmore</strong></p>\n');
document.write('                                </li>\n');
document.write('                                <li><a class=\"dropdown-item\" href=\"#\"><span class=\"icon me-2\"><i class=\"fa-solid fa-circle-user\"></i></span>Tài khoản của tôi</a></li>\n');
document.write('                                <li><a class=\"dropdown-item\" href=\"#\"><span class=\"icon me-2\"><i class=\"fa-solid fa-box\"></i></span>Thông tin gói dịch vụ</a></li>\n');
document.write('                                <li>\n');
document.write('                                    <hr class=\"dropdown-divider\">\n');
document.write('                                </li>\n');
document.write('                                <li><a class=\"dropdown-item\" href=\"login.html\">Đăng xuất</a></li>\n');
document.write('                            </ul>\n');
document.write('                        </li>\n');
document.write('                    </ul>\n');
document.write('                    <!-- END Header Nav End -->\n');
document.write('                </div>\n');
document.write('            </div>\n');
document.write('        </div>\n');
document.write('        <!-- END Site Header -->');