document.write('<!-- BEGIN Site Sidebar -->\n');
document.write('        <div class=\"site-sidebar\">\n');
document.write('            <div class=\"sidebar-header px-3 py-2\">\n');
document.write('                <!-- BEGIN Site Brand -->\n');
document.write('                <div class=\"site-brand\">\n');
document.write('                    <h1 class=\"site-title mb-0\">\n');
document.write('                        <a href=\"index.html\" class=\"site-link\"><img src=\"img/logo-full.svg\" class=\"site-logo full\" alt=\"\"><img src=\"img/logo-icon.svg\" class=\"site-logo icon\" alt=\"\"></a>\n');
document.write('                    </h1>\n');
document.write('                </div>\n');
document.write('                <!-- END Site Brand -->\n');
document.write('                <button class=\"btn btn-white btn-notications bg-transparent\"><i class=\"fa-regular fa-bell\"></i></button>\n');
document.write('            </div>\n');
document.write('            <!-- BEGIN Sidebar Content -->\n');
document.write('            <div class=\"sidebar-content px-3 py-2\">\n');
document.write('                <!-- BEGIN User BLock -->\n');
document.write('                <div class=\"sidebar-user-block mb-3\">\n');
document.write('                    <a href=\"profile.html\" class=\"user-link d-block text-white\">\n');
document.write('                        <div class=\"item-user d-flex align-items-center\">\n');
document.write('                            <div class=\"flex-shrink-0 item-thumb\">\n');
document.write('                                <img src=\"img/temp/avatar_image_0.jpg\" class=\"avatar-image rounded-circle\" alt=\"\">\n');
document.write('                            </div>\n');
document.write('                            <div class=\"flex-grow-1 item-content mt-1 ms-3\">\n');
document.write('                                <h6 class=\"mb-0\"><strong>Anh Minh</strong></h6>\n');
document.write('                                <p class=\"mb-0 small opacity-50\">Quản trị viên</p>\n');
document.write('                            </div>\n');
document.write('                        </div>\n');
document.write('                    </a>\n');
document.write('                </div>\n');
document.write('                <!-- END User BLock -->\n');
document.write('                <!-- BEGIN Sidebar Menu Tree -->\n');
document.write('                <ul class=\"sidebar-menu tree\" data-widget=\"tree\">\n');
document.write('                    <li class=\"treeview active\">\n');
document.write('                        <a href=\"index.html\"><i class=\"fa-solid fa-house\"></i>  <span>Trang chủ</span> <span class=\"pull-right-container\"><i class=\"fa fa-angle-right pull-right\"></i></span></a>\n');
document.write('                    </li>\n');
document.write('                    <li class=\"treeview\"><a href=\"javascript:;\"><i class=\"fa-solid fa-users\"></i>  <span>Người dùng</span> <span class=\"pull-right-container\"><i class=\"fa fa-angle-right pull-right\"></i></span></a>\n');
document.write('                        <ul class=\"treeview-menu\">\n');
document.write('                            <li><a href=\"javascript:;\"><i class=\"fa-solid fa-plus\"></i>  <span>Thêm người dùng</span></a></li>\n');
document.write('                            <li class=\"active\"><a href=\"javascript:;\"><i class=\"fa-solid fa-list\"></i>  <span>Danh sách người dùng</span></a></li>\n');
document.write('                            <li><a href=\"javascript:;\"><i class=\"fa-solid fa-folder\"></i>  <span>Nhóm khách hàng</span></a></li>\n');
document.write('                        </ul>\n');
document.write('                    </li>\n');
document.write('                    <li class=\"treeview\"><a href=\"javascript:;\"><i class=\"fa-solid fa-user\"></i>  <span>Nhân viên</span> <span class=\"pull-right-container\"><i class=\"fa fa-angle-right pull-right\"></i></span></a>\n');
document.write('                        <ul class=\"treeview-menu\">\n');
document.write('                            <li><a href=\"javascript:;\"><i class=\"fa-solid fa-plus\"></i>  <span>Thêm mới nhân viên</span></a></li>\n');
document.write('                            <li><a href=\"javascript:;\"><i class=\"fa-solid fa-list\"></i>  <span>Danh sách nhân viên</span></a></li>\n');
document.write('                            <li><a href=\"javascript:;\"><i class=\"fa-solid fa-folder\"></i>  <span>Nhóm nhân viên</span></a></li>\n');
document.write('                        </ul>\n');
document.write('                    </li>\n');
document.write('                    <li class=\"treeview\"><a href=\"javascript:;\"><i class=\"fa-sharp fa-solid fa-screen-users\"></i>  <span>Nhóm các quyền</span> <span class=\"pull-right-container\"><i class=\"fa fa-angle-right pull-right\"></i></span></a>\n');
document.write('                        <ul class=\"treeview-menu\">\n');
document.write('                            <li><a href=\"javascript:;\"><i class=\"fa-solid fa-plus\"></i>  <span>Quyền cho người dùng</span></a></li>\n');
document.write('                            <li><a href=\"javascript:;\"><i class=\"fa-solid fa-list\"></i>  <span>Nhóm các quyền</span></a></li>\n');
document.write('                        </ul>\n');
document.write('                    </li>\n');
document.write('                    <li class=\"treeview\"><a href=\"javascript:;\"><i class=\"fa-solid fa-box\"></i> <span>Dịch vụ</span> <span class=\"pull-right-container\"><i class=\"fa fa-angle-right pull-right\"></i></span></a>\n');
document.write('                        <ul class=\"treeview-menu\">\n');
document.write('                            <li><a href=\"javascript:;\"><i class=\"fa-solid fa-plus\"></i>  <span>Tạo mới gói dịch vụ</span></a></li>\n');
document.write('                            <li><a href=\"javascript:;\"><i class=\"fa-solid fa-list\"></i>  <span>Danh sách dịch vụ</span></a></li>\n');
document.write('                            <li><a href=\"javascript:;\"><i class=\"fa-solid fa-folder\"></i>  <span>Nhóm dịch vụ</span></a></li>\n');
document.write('                        </ul>\n');
document.write('                    </li>\n');
document.write('                    <li class=\"treeview\"><a href=\"javascript:;\"><i class=\"fa-solid fa-address-card\"></i>  <span>Hợp đồng</span> <span class=\"pull-right-container\"><i class=\"fa fa-angle-right pull-right\"></i></span></a>\n');
document.write('                        <ul class=\"treeview-menu\">\n');
document.write('                            <li><a href=\"javascript:;\"><i class=\"fa-solid fa-plus\"></i>  <span>Thêm mới hợp đồng</span></a></li>\n');
document.write('                            <li><a href=\"javascript:;\"><i class=\"fa-solid fa-list\"></i>  <span>Danh sách hợp đồng</span></a></li>\n');
document.write('                            <li><a href=\"javascript:;\"><i class=\"fa-solid fa-folder\"></i>  <span>Nhóm hợp đồng</span></a></li>\n');
document.write('                        </ul>\n');
document.write('                    </li>\n');
document.write('                    <li class=\"treeview\"><a href=\"javascript:;\"><i class=\"fa-solid fa-hundred-points\"></i>  <span>Khách hàng</span> <span class=\"pull-right-container\"><i class=\"fa fa-angle-right pull-right\"></i></span></a>\n');
document.write('                        <ul class=\"treeview-menu\">\n');
document.write('                            <li><a href=\"javascript:;\"><i class=\"fa-solid fa-list\"></i>  <span>Danh sách khách hàng</span></a></li>\n');
document.write('                            <li><a href=\"javascript:;\"><i class=\"fa-solid fa-setting\"></i>  <span>Cấu hình Welly Points</span></a></li>\n');
document.write('                        </ul>\n');
document.write('                    </li>\n');
document.write('                    <li class=\"treeview\"><a href=\"javascript:;\"><i class=\"fa-solid fa-dumbbell\"></i>  <span>Lớp học</span> <span class=\"pull-right-container\"><i class=\"fa fa-angle-right pull-right\"></i></span></a>\n');
document.write('                        <ul class=\"treeview-menu\">\n');
document.write('                            <li><a href=\"javascript:;\"><i class=\"fa-solid fa-plus\"></i>  <span>Thêm mới lớp học</span></a></li>\n');
document.write('                            <li><a href=\"javascript:;\"><i class=\"fa-solid fa-list\"></i>  <span>Danh sách lớp học</span></a></li>\n');
document.write('                            <li><a href=\"javascript:;\"><i class=\"fa-solid fa-folder\"></i>  <span>Nhóm lớp học</span></a></li>\n');
document.write('                        </ul>\n');
document.write('                    </li>\n');
document.write('                    <li class=\"treeview\"><a href=\"javascript:;\"><i class=\"fa-solid fa-chart-simple\"></i>  <span>Báo cáo</span> <span class=\"pull-right-container\"><i class=\"fa fa-angle-right pull-right\"></i></span></a>\n');
document.write('                        <ul class=\"treeview-menu\">\n');
document.write('                            <li><a href=\"javascript:;\"><i class=\"fa-solid fa-plus\"></i>  <span>Báo cáo tài chính</span></a></li>\n');
document.write('                            <li><a href=\"javascript:;\"><i class=\"fa-solid fa-list\"></i>  <span>Số quỹ</span></a></li>\n');
document.write('                            <li><a href=\"javascript:;\"><i class=\"fa-solid fa-folder\"></i>  <span>Nhắc lịch</span></a></li>\n');
document.write('                        </ul>\n');
document.write('                    </li>\n');
document.write('                </ul>\n');
document.write('                <!-- END Sidebar Menu Tree -->\n');
document.write('            </div>\n');
document.write('            <!-- END Sidebar Content -->\n');
document.write('            <!-- BEGIN Sidebar Footer -->\n');
document.write('            <div class=\"sidebar-footer px-3 py-2\">\n');
document.write('                <button class=\"btn btn-white btn-sidebar-toggle\"><i class=\"fa-solid fa-angles-left\"></i></button>\n');
document.write('            </div>\n');
document.write('            <!-- END Sidebar Footer -->\n');
document.write('        </div>\n');
document.write('        <!-- END Site Sidebar -->');